spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pomin
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
