spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: dev
    import: dev/application-db.yml, dev/application-payment.yml
---
spring:
  mvc:
    view:
      prefix: classpath:/templates/
