spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
  config:
    import: sub/application-kakao.yml, dev/application-jwt.yml, dev/application-payment.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import: dev/application-db.yml
  mvc:
    view:
      prefix: classpath:/templates/
---
spring:
  config:
    activate:
      on-profile: prod
    import: sub/application-db.yml
